### ISSUE TITLE
[질문] peerBuffer to ByteBuffer

### ISSUE THREAD

**Issue by phlox11** [essems/REDFramework-ANDROID#3]
안녕하세요?

RWatcherListener.onFrameLoaded()의 peerBuffer의 data를
allocateDirect()로 미리 할당된 ByteBuffer로 복사하고 싶습니다.

제가 android를 잘 몰라서 그럴수도 있겠지만, Java 영역에서 할 수 있는 방법을 모르겠네요.
혹시 PeerMemory class에서 byte array로 복사해주는 allocateByteArray()와 같이
ByteBuffer로 복사해주는 함수를 만들어 주실 수 있으신지요?
void copyToByteBuffer(long srcPeerBuffer, ByteBuffer dstByteBuffer, int length);
의 형식이면 될 것 같습니다.

**Comment by essems** [comment]
JAVA영역에서 할수 있는지는 모르겠지만. 
아마도 JNI를 사용해서 관련 함수를 구현해 사용하시는게 좋을듯합니다. 

검색해보니.. read하는 부분이 있네요.. 
http://stackoverflow.com/questions/6728616/how-to-read-a-bytearray-in-jni

http://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html
위 JNI 공식 문서의 GetPrimitiveArrayCritical 부분을 참고하시기바랍니다.

**Comment by phlox11** [comment]
아 네
