### ISSUE TITLE
수신 FPS 관련 이슈

### ISSUE THREAD

**Issue by phlox11** [essems/REDFramework-ANDROID#4]
안녕하세요?

현재, 수신 FPS 관련해서
수신된 프레임이 0일 경우 기존 값을 계속 전달해주는 문제가 있는 것으로 알고 있습니다.
즉, 이전 호출 시 20 FPS를 반환했고, 다음 호출 사이에 수신 프레임이 0일 경우
0을 반환해야 하는데 20을 반환합니다.

확인 부탁합니다.

(*) iOS도 같은 현상이 있습니다.

**Comment by essems** [comment]
네트워크 사용량 측정이 영상 수신시에만 업데이트되어, 
수신되지 않는 카메라는 데이터가 업데이트되지 않고 있었습니다.
관련 문제를 수정하여 전달해드리도록 하겠습니다.

**Comment by essems** [comment]
v1.2.0 에 위 내용이 수정되었습니다.
확인해주시기 바랍니다.
